### ISSUE TITLE
data

### ISSUE THREAD

**Issue by liangbingzhao** [baaivision/vid2vid-zero#1]
I found child-riding.mp4 is green. Hope u update the data folder. 
Btw, it is really a great work. Congrats!

**Comment by encounter1997** [comment]
Hi, thanks for your interest. But we don't seem to have this issue and the data looks normal after cloning. Could you provide more details?

**Comment by liangbingzhao** [comment]
After I download, the child-riding.mp4 would be like this.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/55656865/231685054-7057c6fe-e3be-4c66-830f-8aebe89c8f10.png">
